"""Tests for scripts/generate_cli_reference.py."""

from __future__ import annotations

import shlex
import subprocess
import sys
from pathlib import Path

import click
import pytest

from scripts import generate_cli_reference as gen

SCRIPT = Path(gen.__file__).resolve()
LIGHTHOUSE = Path(sys.executable).parent / "lighthouse"

# Fake CLI: prints a deterministic help per path; fails for any path containing "preview".
FAKE_CLI = """\
import sys
args = [a for a in sys.argv[1:] if a != "--help"]
if "preview" in args:
    sys.stderr.write("boom: preview help broke\\n")
    raise SystemExit(3)
print("help for", " ".join(["lighthouse", *args]))
"""


def _fake_cli(tmp_path: Path) -> str:
    script = tmp_path / "fake_cli.py"
    script.write_text(FAKE_CLI, encoding="utf-8")
    return shlex.join([sys.executable, str(script)])


def _run_script(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        capture_output=True,
        text=True,
        check=False,
        cwd=SCRIPT.parent.parent,
    )


class _LazyGroup(click.Group):
    """Mimics the repo's lazy groups: children resolved only via get_command."""

    def __init__(self, name: str, target: click.Group) -> None:
        super().__init__(name=name)
        self._target = target

    def list_commands(self, ctx: click.Context) -> list[str]:
        return self._target.list_commands(ctx)

    def get_command(self, ctx: click.Context, cmd_name: str) -> click.Command | None:
        return self._target.get_command(ctx, cmd_name)


def _synthetic_tree() -> click.Group:
    @click.group()
    def root() -> None: ...

    @click.group()
    def impl() -> None: ...

    @impl.group()
    def preview() -> None: ...

    @preview.group()
    def deep() -> None: ...

    @deep.command()
    def leaf() -> None: ...

    @preview.command(hidden=True)
    def secret() -> None: ...

    @impl.command()
    def plain() -> None: ...

    root.add_command(_LazyGroup("instructor", impl))
    return root


def test_command_paths_recurse_through_lazy_groups_at_any_depth() -> None:
    paths = gen.command_paths(_synthetic_tree())
    assert paths == [
        (),
        ("instructor",),
        ("instructor", "plain"),
        ("instructor", "preview"),
        ("instructor", "preview", "deep"),
        ("instructor", "preview", "deep", "leaf"),
    ]


def test_real_tree_includes_nested_instructor_preview_commands() -> None:
    paths = gen.command_paths(gen.load_root())
    preview = [p for p in paths if p[:2] == ("instructor", "preview") and len(p) == 3]
    assert {p[2] for p in preview} >= {"start", "answer", "next", "page", "submit", "status"}
    assert max(len(p) for p in paths) >= 3


def test_success_writes_output_atomically(tmp_path: Path) -> None:
    ok = tmp_path / "ok_cli.py"
    ok.write_text('import sys\nprint("help for", *sys.argv[1:-1])\n', encoding="utf-8")
    out_dir = tmp_path / "out"
    dest = out_dir / "cli-reference.md"

    code = gen.main(["--output", str(dest), "--cli", shlex.join([sys.executable, str(ok)])])

    assert code == 0
    text = dest.read_text(encoding="utf-8")
    assert text.startswith("<!-- Generated by scripts/generate_cli_reference.py")
    assert "##### `lighthouse instructor preview start`" in text
    assert "help for instructor preview start" in text
    assert list(out_dir.iterdir()) == [dest]  # no stray temp files


def test_failed_help_exits_cleanly_and_leaves_destination_unchanged(tmp_path: Path) -> None:
    dest = tmp_path / "cli-reference.md"
    original = b"original \xe2\x80\x94 content\r\nkept byte-for-byte\n"
    dest.write_bytes(original)

    result = _run_script("--output", str(dest), "--cli", _fake_cli(tmp_path))

    assert result.returncode != 0
    assert "Traceback" not in result.stderr
    assert "CalledProcessError" not in result.stderr
    assert result.stderr.startswith("error: ")
    assert "preview" in result.stderr
    assert len(result.stderr.splitlines()) == 1
    assert dest.read_bytes() == original
    assert set(tmp_path.iterdir()) == {dest, tmp_path / "fake_cli.py"}  # no stray temp files


def test_missing_cli_executable_is_a_clean_error(tmp_path: Path) -> None:
    dest = tmp_path / "cli-reference.md"
    result = _run_script("--output", str(dest), "--cli", "definitely-not-a-real-cli-xyz")
    assert result.returncode == 1
    assert "Traceback" not in result.stderr
    assert not dest.exists()


@pytest.fixture(scope="module")
def generated_reference(tmp_path_factory: pytest.TempPathFactory) -> str:
    if not LIGHTHOUSE.exists():
        pytest.skip("lighthouse console script not installed next to the interpreter")
    dest = tmp_path_factory.mktemp("ref") / "cli-reference.md"
    assert gen.main(["--output", str(dest), "--cli", str(LIGHTHOUSE)]) == 0
    return dest.read_text(encoding="utf-8")


def test_every_click_command_path_appears_in_generated_doc(generated_reference: str) -> None:
    for path in gen.command_paths(gen.load_root()):
        heading = " ".join(["lighthouse", *path])
        assert f" `{heading}`\n" in generated_reference, heading
        assert f"Usage: {heading} " in generated_reference, heading


def test_generated_doc_covers_instructor_preview_subcommands(generated_reference: str) -> None:
    for sub in ("start", "answer", "next", "page", "submit", "status", "abandon"):
        assert f"##### `lighthouse instructor preview {sub}`" in generated_reference
        assert f"Usage: lighthouse instructor preview {sub} " in generated_reference
