#!/usr/bin/env python3
"""Regenerate docs/cli-reference.md from verbatim ``--help`` output.

Usage:
    python scripts/generate_cli_reference.py > docs/cli-reference.md
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys

SKIP_TOKENS = {"--version", "--help", "COMMAND", "[ARGS]...", "OPTIONS:", "Commands:"}


def run_help(cli: list[str], args: list[str]) -> str:
    result = subprocess.run(cli + args + ["--help"], capture_output=True, text=True, check=True)
    return result.stdout.strip()


def subcommands(text: str) -> list[str]:
    found = []
    for match in re.finditer(r"^  (\S+)\s{2,}(.*)$", text, re.MULTILINE):
        name = match.group(1)
        if name.startswith("-") or name in SKIP_TOKENS:
            continue
        if "Commands:" in text:
            found.append(name)
    return found


def main() -> int:
    cli = [str(part) for part in (sys.argv[1:] or ["lighthouse"])]
    if shutil.which(cli[0]) is None:
        print(f"error: {cli[0]!r} not found on PATH", file=sys.stderr)
        return 1

    out = [
        "<!-- Generated by scripts/generate_cli_reference.py — do not edit by hand. -->",
        "",
        "# CLI reference",
        "",
        "Verbatim `--help` output for every command (top level, groups, and leaf",
        "commands). Regenerate after changing commands:",
        "",
        "```sh",
        "python scripts/generate_cli_reference.py > docs/cli-reference.md",
        "```",
        "",
    ]

    def emit(args: list[str], depth: int) -> None:
        text = run_help(cli, args)
        heading = "lighthouse" + (" " + " ".join(args) if args else "")
        out.append("#" * depth + " `" + heading + "`")
        out.extend(["", "```text", text, "```", ""])

    emit([], 2)
    for cmd in subcommands(run_help(cli, [])):
        emit([cmd], 3)
        for sub in subcommands(run_help(cli, [cmd])):
            emit([cmd, sub], 4)

    print("\n".join(out).rstrip())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
