#!/usr/bin/env python3
"""Regenerate docs/cli-reference.md from verbatim ``--help`` output.

Usage:
    python scripts/generate_cli_reference.py [--output PATH] [--cli COMMAND]

Options:
    --output PATH   Destination file (default: docs/cli-reference.md at the
                    repository root). The file is written atomically: output is
                    generated into a temporary file in the destination directory
                    and moved into place only after every ``--help`` succeeded,
                    so a failed run leaves the destination byte-for-byte
                    unchanged. Use ``-`` to print to stdout instead.
    --cli COMMAND   Command used to invoke the CLI (default: ``lighthouse``;
                    split with shell rules, e.g. ``--cli "python -m foo"``).

Subcommands are discovered by walking the real Click command tree
(``lighthouse_cli.cli:cli``) through ``list_commands``/``get_command``, so
lazily loaded groups (``instructor``/``student`` and their nested groups such
as ``instructor preview``) are covered at any depth. Hidden commands are
skipped. Help text itself is captured by running ``<cli> <path...> --help``.
"""

from __future__ import annotations

import argparse
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Sequence
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import click

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "cli-reference.md"
PROG_NAME = "lighthouse"
MAX_HEADING_LEVEL = 6

HEADER = [
    "<!-- Generated by scripts/generate_cli_reference.py — do not edit by hand. -->",
    "",
    "# CLI reference",
    "",
    "Verbatim `--help` output for every command (top level, groups, and leaf",
    "commands, at any nesting depth). Regenerate after changing commands:",
    "",
    "```sh",
    "python scripts/generate_cli_reference.py",
    "```",
    "",
]


class HelpError(RuntimeError):
    """Raised when ``--help`` cannot be captured for a command path."""


def command_paths(root: click.Command, prog_name: str = PROG_NAME) -> list[tuple[str, ...]]:
    """Return every visible command path in ``root``, depth-first, sorted per level.

    The root itself is the empty tuple. Groups are resolved through Click's
    ``list_commands``/``get_command`` so lazy groups load their real children.
    """
    paths: list[tuple[str, ...]] = []

    def walk(command: click.Command, ctx: click.Context, path: tuple[str, ...]) -> None:
        paths.append(path)
        if not isinstance(command, click.Group):
            return
        for name in command.list_commands(ctx):
            child = command.get_command(ctx, name)
            if child is None or child.hidden:
                continue
            child_ctx = click.Context(child, info_name=name, parent=ctx)
            walk(child, child_ctx, (*path, name))

    walk(root, click.Context(root, info_name=prog_name), ())
    return paths


def run_help(cli: Sequence[str], path: Sequence[str]) -> str:
    """Capture ``<cli> <path...> --help`` stdout, raising HelpError on failure."""
    argv = [*cli, *path, "--help"]
    label = " ".join([PROG_NAME, *path])
    try:
        result = subprocess.run(
            argv,
            capture_output=True,
            text=True,
            check=False,
            env={**os.environ, "COLUMNS": "80"},  # Click wraps help at <=80; pin it
        )
    except OSError as exc:
        raise HelpError(f"could not run {label!r} --help: {exc}") from exc
    if result.returncode != 0:
        detail = result.stderr.strip().splitlines()
        suffix = f": {detail[-1]}" if detail else ""
        raise HelpError(f"{label!r} --help exited with status {result.returncode}{suffix}")
    return result.stdout.strip()


def render(cli: Sequence[str], paths: Sequence[tuple[str, ...]]) -> str:
    """Render the markdown reference for ``paths`` (help captured in parallel)."""
    with ThreadPoolExecutor(max_workers=min(8, max(1, len(paths)))) as pool:
        helps = list(pool.map(lambda path: run_help(cli, path), paths))

    out = list(HEADER)
    for path, text in zip(paths, helps, strict=True):
        level = min(2 + len(path), MAX_HEADING_LEVEL)
        heading = " ".join([PROG_NAME, *path])
        out.append("#" * level + " `" + heading + "`")
        out.extend(["", "```text", text, "```", ""])
    return "\n".join(out).rstrip() + "\n"


def write_atomic(dest: Path, content: str) -> None:
    """Write ``content`` to ``dest`` via a same-directory temp file + os.replace."""
    dest.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=f".{dest.name}.", suffix=".tmp", dir=dest.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
        os.replace(tmp_name, dest)
    except BaseException:
        Path(tmp_name).unlink(missing_ok=True)
        raise


def load_root() -> click.Command:
    from lighthouse_cli.cli import cli

    return cli


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate the CLI reference markdown.")
    parser.add_argument(
        "-o",
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="destination file, or '-' for stdout (default: docs/cli-reference.md)",
    )
    parser.add_argument(
        "--cli",
        default=PROG_NAME,
        help="command used to invoke the CLI (default: lighthouse)",
    )
    args = parser.parse_args(argv)

    cli = shlex.split(args.cli)
    if not cli:
        print("error: --cli must not be empty", file=sys.stderr)
        return 2
    if shutil.which(cli[0]) is None:
        print(f"error: {cli[0]!r} not found on PATH", file=sys.stderr)
        return 1

    try:
        content = render(cli, command_paths(load_root()))
    except HelpError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.output == "-":
        sys.stdout.write(content)
        return 0
    try:
        write_atomic(Path(args.output), content)
    except OSError as exc:
        print(f"error: could not write {args.output}: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
